services:
  web:
    #image: ghcr.io/adotbyte/resume_website:latest
    build: .
    container_name: resume_website
    restart: unless-stopped
    # We use the full path so OMV can't miss it
    env_file:
    - .env
    volumes:
      - ./.env:/home/app/web/.env
      - .:/code
      - ./chroma_db:/code/chroma_db
    ports:
      - "8080:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s