"""
Django settings for CV project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CHROMA_DB_PATH = os.path.join(BASE_DIR, "chroma_db")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Initialize env
env = environ.Env()

# Explicitly tell django-environ where the .env file is
env_file = os.path.join(BASE_DIR, ".env")

if os.path.exists(env_file):
    environ.Env.read_env(env_file)
else:
    print("Warning: .env file not found at", env_file)

# Now read the key Django
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
env = environ.Env(
    DEBUG=(bool, False)
)
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# Gemini API security key

env = environ.Env()
# This reads the actual .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

GEMINI_API_KEY = env('GEMINI_API_KEY')

FB_APP_ID = os.getenv('FB_APP_ID')

#GOOGLE_CLOUD_PROJECT = env('GOOGLE_CLOUD_PROJECT')

# Sesion
SESSION_SAVE_EVERY_REQUEST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'corsheaders',
    'index',
    'sendemail',
    'turnstile',
    'crispy_forms',
    'crispy_bootstrap5',
    'config',  
    #'blog',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Best place for static files
    'django.contrib.sessions.middleware.SessionMiddleware', # Session MUST be before CSRF
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware', # CSRF MUST be after Session
    'csp.middleware.CSPMiddleware',
    'config.middleware.SecurityHeadersMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# React
CORS_ALLOW_ALL_ORIGINS = True

### turnstile
TURNSTILE_SITE_KEY = env('VITE_TURNSTILE_SITE_KEY', default='')
TURNSTILE_SECRET_KEY = env('TURNSTILE_SECRET_KEY', default='')

TURNSTILE_DEFAULT_CONFIG = {
    'theme': 'auto',    # Options: 'light', 'dark', or 'auto'
    'size': 'compact',   # Options: 'normal', 'flexible', or 'compact'
}

### sitemap.xml
SITE_ID = 1

# posthog telemetry disable
os.environ['ANONYMIZED_TELEMETRY'] = 'False'

# Since you're behind Cloudflare
SECURE_PROXY_SSL_HEADER = ('HTTP_CF_VISITOR', '{"scheme":"https"}')
# --- Find your SECURE_PROXY settings and use this single block ---
# Cloudflare uses 'HTTP_CF_VISITOR' or 'HTTP_X_FORWARDED_PROTO'
# For HTTPS sites ensure cookies are only sent over HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSP_EXCLUDE_URL_PREFIXES = ()
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

if not DEBUG:
    # 1 year in seconds (31,536,000)
    SECURE_HSTS_SECONDS = 31536000 
    
    # Apply HSTS to all subdomains (e.g., www.morkunas.info)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    
    # Allow the site to be submitted to the HSTS preload list
    SECURE_HSTS_PRELOAD = True
    
    # Redirect all HTTP traffic to HTTPS inside Django
    SECURE_SSL_REDIRECT = True

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True 
SESSION_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = [
    'localhost',
    'http://127.0.0.1:8000',
    'https://morkunas.info',
    'https://www.morkunas.info',
]
CSRF_USE_SESSIONS = True
CSRF_COOKIE_NAME = 'csrftoken'

# Add the prefixes to satisfy the "No Cookie Prefix" warning
SESSION_COOKIE_NAME = 'sessionid'
CSRF_COOKIE_NAME = '__Host-csrftoken'

# LAX
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# TEMPORARY: ONLY for local development to bypass the login block
CSRF_AUTO_RELOAD_HEADERS = True

### settings.py - Production CSP Configuration
### settings.py - Unified CSP Configuration

# settings.py

CSP_DEFAULT_SRC = ("'self'", "https://morkunas.info", "https://www.morkunas.info")

CSP_SCRIPT_SRC = (
    "'self'", 
    "https://cdn.jsdelivr.net",
    "https://cdn.tailwindcss.com",          # Allow Tailwind CDN
    "https://challenges.cloudflare.com",    # Allow Turnstile
    "https://cdnjs.cloudflare.com", 
    "'unsafe-inline'",                      # Needed for the window.KEY injection
    "'unsafe-eval'",                        # Needed for React
)

CSP_STYLE_SRC = (
    "'self'", 
    "https://cdn.jsdelivr.net", 
    "https://fonts.googleapis.com",
    "https://cdn.tailwindcss.com",          # Allow Tailwind Styles
    "'unsafe-inline'",                      # CRITICAL: Tailwind needs this to inject CSS
)

CSP_FRAME_SRC = ("'self'", "https://challenges.cloudflare.com")
CSP_CONNECT_SRC = ("'self'", "https://challenges.cloudflare.com", "https://cloudflareinsights.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")

# This ensures your <script nonce="..."> tags in base.html work
CSP_INCLUDE_NONCE_IN = ['script-src', 'style-src']

### Other things

ROOT_URLCONF = 'config.urls'

# X-Frame-Options
X_FRAME_OPTIONS = 'DENY'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend', 'dist'), # React folder
            BASE_DIR / "templates",                    # Old templates folder
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'index.context_processors.chat_history_processor',
                'index.context_processors.sync_info',
                'index.context_processors.fb_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Vilnius'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    # Point to 'dist', NOT 'dist/assets'
    # This allows Django to find '/assets/index.js' correctly
    BASE_DIR / 'frontend' / 'dist',
]
# Optional: compressed and cached files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings

from decouple import config

# ---- Email Configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "sent_emails"  # directory where emails will be stored

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)  # Must be .int()
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS') # Must be .bool()
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# ---- Email Form

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
NOTIFY_EMAIL = env('NOTIFY_EMAIL')

# Crispy forms
# Tell crispy which template pack to use
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# List of allowed domains email domain 
ALLOWED_DOMAINS = ['gmail.com', 'yahoo.com', 'yourdomain.com', '.lt', '.com', '.net', '.org', '.edu', '.gov', '.info', '.eu']
ALLOWED_SUFFIXES = ['.lt', '.com', '.net', '.org', '.edu', '.gov', '.info', '.eu']

# URL to access uploaded files
#MEDIA_URL = '/media/'

# Directory on the server to store uploaded files
#MEDIA_ROOT = BASE_DIR / 'media'

# Redirect all HTTP requests to HTTPS (Cloudflare usually does this, 
# but this is a good backup)
SECURE_SSL_REDIRECT = False # Change to True when deployment

# Silence warning
SILENCED_SYSTEM_CHECKS = ["security.W004"]

# If using subdomains
CSRF_TRUSTED_ORIGINS = [
    'https://morkunas.info',
    'https://www.morkunas.info',
]

# In settings.py (for debugging only)



