name: Native Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run this manually from the GitHub UI

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        env:
          MY_GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Mapping Repository Secrets to Shell Variables
          RS_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          RS_EMAIL_USER: ${{ secrets.EMAIL_HOST_USER }}
          RS_EMAIL_PASS: ${{ secrets.EMAIL_HOST_PASSWORD }}
          RS_NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
          RS_EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          RS_EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          RS_EMAIL_TLS: ${{ secrets.EMAIL_USE_TLS }}
          RS_GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
          RS_DEBUG: ${{ secrets.DEBUG }}
          RS_ALLOWED: ${{ secrets.ALLOWED_HOSTS }}
          RS_FB_APP_ID: ${{ secrets.FB_APP_ID }}
        run: |
          # Go to your specific server folder
          cd /home/audrius/actions-runner/_work/resume_website/resume_website
          
          # 2. Use the mapped variable (MY_GEMINI_KEY) to write the file
          # Use double quotes to handle any special characters in the key
          echo "GEMINI_API_KEY=\"$MY_GEMINI_KEY\"" > .env

          cat <<EOF > .env
          SECRET_KEY="$RS_SECRET_KEY"
          EMAIL_HOST_USER="$RS_EMAIL_USER"
          EMAIL_HOST_PASSWORD="$RS_EMAIL_PASS"
          NOTIFY_EMAIL="$RS_NOTIFY_EMAIL"
          EMAIL_HOST="$RS_EMAIL_HOST"
          EMAIL_PORT=${RS_EMAIL_PORT:-587}
          EMAIL_USE_TLS=${RS_EMAIL_TLS:-True}
          GEMINI_API_KEY="$RS_GEMINI_KEY"
          DEBUG=${RS_DEBUG:-False}
          ALLOWED_HOSTS="$RS_ALLOWED"
          FB_APP_ID="$RS_FB_APP_ID"
          EOF
          echo "Success: .env file created with variables."

      - name: Build and Restart
        run: |
          # This builds the image NATIVELY on your Raspberry Pi
          docker compose build --pull
          docker compose up -d --force-recreate
          
          # Clean up old unused images to save SD card space
          docker image prune -f

      - name: Verify Deployment
        run: |
          echo "Waiting for container to stabilize..."
          sleep 10
          
          # Check the Docker health status
          STATUS=$(docker inspect --format='{{json .State.Health.Status}}' resume_website)
          
          if [ "$STATUS" = "\"healthy\"" ]; then
            echo "Website is UP and Healthy!"
          else
            echo "Website is UNHEALTHY or CRASHED. Current status: $STATUS"
            docker logs resume_website
            exit 1
          fi