name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64  # This ensures it works on Raspberry Pi 5
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
  deploy:
        needs: build  # Only run if the build finishes successfully
        runs-on: self-hosted  # Use your Audrius server runner
        steps:
          - name: Create .env file
            run: |
              # Go to your project folder
              cd /home/audrius/actions-runner/_work/resume_website/resume_website/CV/CV/
              
              # Create the fresh .env from GitHub Secrets
              echo "SECRET_KEY=${{ secrets.MY_SECRET_KEY }}" > .env
              # Add other keys here if you have them
              
          - name: Pull and Restart Docker
            run: |
              cd /home/audrius/actions-runner/_work/resume_website/resume_website/CV/CV/
              
              # 1. Pull the fresh image you just built
              docker compose pull
              
              # 2. Restart the container with the new image and the new .env
              docker compose up -d --force-recreate